version: '2'

services:

       registry:
            image: registry
            ports:
                - "5000:5000" 
       ui:
            image: konradkleine/docker-registry-frontend
            environment:
                - ENV_DOCKER_REGISTRY_HOST=registry
                - ENV_DOCKER_REGISTRY_PORT=5000
            ports:
                - "8083:80" 
