
serverA:
        image: demo-server

serverB:
        image: demo-server

loadbalancer:
        image: demo-loadbalancer
        links:
                - serverA:app1
                - serverB:app2
        ports:
                - 8080:8080

