version: '3.3'

services:

    wordpress:
        image: wordpress
        environment:
            - WORDPRESS_DB_PASSWORD=ichsinge1234
        volumes:
            - /etc/localtime:/etc/localtime:ro
        ports:
            - "80:80"

    mysql:
        image: mariadb
        environment:
            - MYSQL_ROOT_PASSWORD=ichsinge1234
        
