version: '3'

services:

    wordpress:
        image: wordpress
        networks:
            - wordpress
        environment:
            - WORDPRESS_DB_PASSWORD=ichsinge1234
        volumes:
            - /etc/localtime:/etc/localtime:ro

    mysql:
        image: mariadb
        networks:
            - wordpress
        environment:
            - MYSQL_ROOT_PASSWORD=ichsinge1234
        
networks:
    wordpress:
