version: '3.4'

# stackname ist portainer !

services:

  portainer:
    image: portainer/portainer
    # password hash generiert mit: docker run --rm httpd:2.4-alpine htpasswd -nbB admin 'geheim' | cut -d ":" -f 2
    command: --host tcp://tasks.portainer_agent:9001 --tlsskipverify --admin-password "$$2y$$05$$GJG/AENcZjB0Ntwo.6b3xuaKDhjbImMP.0KAFFbXI3o2Dk5BP3xKi"
    volumes:
      - portainer:/data
    networks:
      traefik:
      agent_network:
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
    ports:
      - "9000:9000"

  agent:
    image: portainer/agent
    environment:
      # REQUIRED: Should be equal to the service name prefixed by "tasks." when
      # deployed inside an overlay network
      AGENT_CLUSTER_ADDR: tasks.portainer_agent
      # AGENT_PORT: 9001
      # LOG_LEVEL: debug
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      agent_network:
    deploy:
      mode: global

volumes:
  portainer:

networks:
  traefik:
  agent_network:
